### ISSUE TITLE
Consider a "protobuf visualizer" which outputs a UTF-8 text stream w/ symbols

### ISSUE THREAD

**Issue by TeamGleasonDev** [TeamGleason/SpeakFaster#12]
Help make the text log human readible by visualizing the output.

Consider using a font w/ symbols so we can insert symbols for complex operations (e.g. speak, select word predict), perhaps add markdown formatting too?

See Glyph Browser to visualize potential font glyphs to use:
https://www.microsoft.com/en-us/p/glyph-browser/9wzdncrdlxt7

**Comment by TeamGleasonDev** [comment]
UI Interactions to visualize:

**Speak** - Ctrl-E
**Pause** - Ctrl-Q
**Stop** - Ctrl-W
**Char Backspace** - Backspace
**Clear All** - Ctrl-A followed by Enter(s) or first letter of new sentence

**Start of Phrase** (First letter after Enter)
**End of Phrase** (Speak)

**Reset of thought** (Ctrl-A without Ctrl-E first)
**Select Word Prediction** - Very rapid backspaces followed by very rapid letter injection
**Word Backspace** - Rapid backspaces in a row

**Select preexisting text** - Mouse Left Click on Text Window followed by Ctrl-W

---

**Calculated Metadata**

WPM for each phrase spoken
Unbroken thought (no pauses or navigations)
Broken thought (pauses, navigations)
Reset thought

Number of Phrases Spoken this session
Number of Broken/Unbroken/Reset thoughts this session
Average WPM this session
Average WPM of thoughts this session
Highest WPM in thought w/ 4 or more words this session (with phrase)

**Comment by TeamGleasonDev** [comment]
Speak: &#x1f4ac;
Stop: &#x1f6d1;
Pause: &#x23f8;

Enter: &#x21a9;

Start Of Text: &#x2402;
End Of Text: &#x2403;
Cancel: &#x2418; (reset of thought)

Backspace: &#x1f820;
Backword: &#x219e;
Clear All: &#x21e4;

Use Prediction: &#x1f5e9;
Change Paragraph: &#x0394;
Change Stemming: &#x241a;

Timing: &#x23f2;

**Comment by TeamGleasonDev** [comment]
Phase 1:

Char Analysis: Speak Stop Pause Enter Backspace
Context Analysis: STX ETX Clear Cancel
Timing Analysis: Backword, Use Prediction, WPM

**Comment by TeamGleasonDev** [comment]
Examples:

␂ H E L K 🠠 L O ␃ 💬 12.3 ⏲
␂ H E L 🗩 HELLO ␃ 💬 16.3 ⏲

**Comment by joncamp** [comment]
How are we defining WPM? Commonly it is 5 chars/word average, so currently assuming CPM/5 = WPM

**Comment by TeamGleasonDev** [comment]
@joncamp https://github.com/TeamGleason/SpeakFaster/blob/main/DefinitionOfWPM.md

**Comment by joncamp** [comment]
Prediction:

> Regarding prediction usage - there is not guarantee of backspaces. The chunk below would be typing "r" "e" "m" and then selecting "remember". As such, we need to look for places where backspaces and/or characters are typed very rapidly - faster than any human could type. Predictions also consistently insert a space at the end
> 
> For example:
> 
> ```
> Key:R Timestamp:1620241346.817684500 Delta:0:00:02.154467 True
> Key:E Timestamp:1620241349.940664900 Delta:0:00:03.122981 True
> Key:M Timestamp:1620241350.980782100 Delta:0:00:01.040117 True
> Key:E Timestamp:1620241350.982065300 Delta:0:00:00.001283 False
> Key:M Timestamp:1620241350.984422800 Delta:0:00:00.002358 False
> Key:B Timestamp:1620241350.986267600 Delta:0:00:00.001845 False
> Key:E Timestamp:1620241350.987553600 Delta:0:00:00.001286 False
> Key:R Timestamp:1620241350.989289300 Delta:0:00:00.001735 False
> Key:Space Timestamp:1620241350.992097100 Delta:0:00:00.002808 False
> ```

Del Word:

> Ctrl->Shift->Left->Backspace in rapid succession
> 
> ```
> Key:LControlKey Timestamp:1620241354.803304200 Delta:0:00:03.811207 True
> Key:LShiftKey Timestamp:1620241354.804177800 Delta:0:00:00.000874 False
> Key:Left Timestamp:1620241354.804785600 Delta:0:00:00.000607 False
> Key:Back Timestamp:1620241354.808022300 Delta:0:00:00.003237 False

```

Cut/Copy/Paste

> Manually driven (note the delays between actions). Windows controls such as ctrl->x, ctrl->c, ctrl->v 
>
> ```
> Key:LControlKey Timestamp:1620244483.428905700 Delta:0:00:09.555277 True
> Key:X Timestamp:1620244484.189253400 Delta:0:00:00.760347 True
> Key:LControlKey Timestamp:1620244495.573422100 Delta:0:00:01.243876 True
> Key:V Timestamp:1620244496.225677400 Delta:0:00:00.652255 True
> ```

**Comment by joncamp** [comment]
Outside of characters, here are the special characters (https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.keys?view=net-5.0):

- Back - Backspace
- D1 - '1'
- LControlKey - left CTRL key
- LShiftKey - left SHIFT key
- LWin - left Windows logo key
- Left - LEFT ARROW
- Oem7 - also OemQuotes. The OEM singled/double quote key on a US standard keyboard.
- OemPeriod - Period
- OemQuestion - Question mark
- Oemcomma - Comma
- Return
- Space
- Tab

**Comment by joncamp** [comment]
Windows Control patterns:

> per https://support.microsoft.com/en-us/windows/keyboard-shortcuts-in-windows-dcc61a57-8ff0-cffe-9796-cb9706c75eec
> 
> Win+A = Open Action Center
> ```
> Key:LWin Timestamp:1620234219.149786900 Delta:0:00:09.355810 True
> Key:A Timestamp:1620234219.155789900 Delta:0:00:00.006003 False
> ```
> 
> Win+s = Open search bar
> ```
> Key:LWin Timestamp:1620234406.422918600 Delta:0:03:01.948512 True
> Key:S Timestamp:1620234406.426892800 Delta:0:00:00.003974 False
> ```
> 
> Win+Tab = Open Task View
> ```
> Key:LWin Timestamp:1620234426.790338900 Delta:0:00:20.363446 True
> Key:Tab Timestamp:1620234426.794202500 Delta:0:00:00.003864 False
> ```
