### ISSUE TITLE
Data manager: Download session seems to skip the concatenated_audio.wav and screenshots.mp4 files

### ISSUE THREAD

**Issue by caisq** [TeamGleason/SpeakFaster#127]

**Comment by seanholmes77** [comment]
I suspect that the Download button just downloads what is needed for the pre-processing steps, and not these additional 2 files once pre-processing completes (no problemo if all steps happen on same device). If so, is there a way to update the logic for the GUI button to include an 'if these files exist: download them too'? Hoping that will make it work as intended both before and after pre-processing.

**Comment by caisq** [comment]
I did some investigation. I think I understand what the issue is, for the session we looked at together yesterday, the merged.tsv file exists in the S3 bucket. But the concatenated_audio.wav and screenshots.mp4 do not exist in the bucket. This might be because the uploading process got interrupted. @seanholmes77 Can you click the "Uploading preprocessing data" button for that session again? Once done, let me know and we can try downloading the session on the other machine again.
