### ISSUE TITLE
Consider moving to .NET Core...

### ISSUE THREAD

**Issue by TeamGleasonDev** [TeamGleason/SpeakFaster#2]
...was looking into adding Github Actions for doing project validation, and it looks like .NET Desktop apps are supported, but only if they are on top of the newer .NET Core platform.

https://github.com/microsoft/github-actions-for-desktop-apps
https://github.com/actions/setup-dotnet
https://devblogs.microsoft.com/dotnet/continuous-integration-workflow-template-for-net-core-desktop-apps-with-github-actions/

**Comment by joncamp** [comment]
The project is currently targeted to .net 5. Per https://docs.microsoft.com/en-us/dotnet/core/dotnet-five, .net 5 is the next major release of .net core 3.1. Per https://www.elliotdenolf.com/posts/build-net-5-applications-with-github-actions/, it looks like it should just work pending verification.

**Comment by TeamGleasonDev** [comment]
Right.  Nice work.
