### ISSUE TITLE
Feature request: Make color LED flash during data collection

### ISSUE THREAD

**Issue by caisq** [TeamGleason/SpeakFaster#31]
The color LED we plan to use is "Sparklet All in One". It can be controlled USB or bluetooth. During data collection, it should flash conspicuously to notify people around of the data collection.

**Comment by TeamGleasonDev** [comment]
Per comment from @joncamp , flashing attracts the eye.  This is an anti-pattern in eye gaze controlled devices.

**Comment by caisq** [comment]
Agreed that flashing attracts the eye. But do we want to at least do something with the LED, e.g., a steady-on state when data is being collected?
