### ISSUE TITLE
Feature request: Make the system tray icon blink during data collection

### ISSUE THREAD

**Issue by caisq** [TeamGleason/SpeakFaster#32]
In order to make ongoing data collection more salient to the user, the system try icon should blink at a rate of about 0.5 Hz, in addition to turning red.

**Comment by joncamp** [comment]
As noted in https://github.com/TeamGleason/SpeakFaster/issues/7, flashing the icon is a visual distraction. We should be *very* careful about anything which would add persistent visual distraction, and as-such potentially negatively impact the results we are collecting. 0.5Hz may be slow enough to not be a distraction, but it is something we should be thoughtful about if we do implement it.
