### ISSUE TITLE
Feature Question: Should we try to calculate actual words via tokenization rather than use the standard "5" characters?

### ISSUE THREAD

**Issue by joncamp** [TeamGleason/SpeakFaster#36]
"I understand 5 is the oft-cited average word length. But ideally, we should use a tokenizer to get the actual # of words for this calculation." per @caisq 

_Originally posted by @caisq in https://github.com/TeamGleason/SpeakFaster/pull/34#discussion_r636135399_

**Comment by TeamGleasonDev** [comment]
I see two downsides here:

- Variance from established pattern
- Penalizing people who use longer words to express throughts

**Comment by joncamp** [comment]
I tend to agree. The 5 WPM metric is industry standard. Being agnostic to the chosen text lets us compare in a more consistent manner.

**Comment by caisq** [comment]
Using the average word length of 5 to calculate WPM sounds good to me. The point about not penalizing people who use longer words is a good one.
