### ISSUE TITLE
Consider making system tray icon blink when recording

### ISSUE THREAD

**Issue by TeamGleasonDev** [TeamGleason/SpeakFaster#7]

**Comment by joncamp** [comment]
Interesting idea. Not technically that difficult. My primary concern is having an active visual distraction on an eye gaze interface seems like an anti-pattern

**Comment by joncamp** [comment]
Closed #32 as duplicate of this

**Comment by TeamGleasonDev** [comment]
Agree with @joncamp's observation that blinky objects on eye gaze system cause unwelcome saccades.
